USER_EMAIL_ALREADY_EXISTS_ERROR = "User with this email already exists."
USER_CREATION_FAILED_ERROR = "Failed to create user due to server error."
USER_UPDATE_FAILED_ERROR = "Failed to update user due to server error."
USER_PASSWORD_INVALID_ERROR = "Password must be a non-empty string."
USER_ID_NOT_EXISTS_ERROR = "User with the provided ID does not exist."
USER_EMAIL_NOT_EXISTS_ERROR = "User with the provided email does not exist."
USER_NOT_FOUND_ERROR = "User not found or does not exist"
